### ISSUE TITLE
Player dies infinitely on join

### ISSUE THREAD

**Issue by HimbeerserverDE** [Minetest-j45/sumo_duels#4]

**Comment by Minetest-j45** [comment]
set static_spawnpoint to 0,100,0 ?, i guess i will add this to readme

**Comment by HimbeerserverDE** [comment]
Why don't you just set it to 0,100,0 automatically?

**Comment by HimbeerserverDE** [comment]
See #5

**Comment by Minetest-j45** [comment]
Closing this issue, #5 has been merged
